# Safestrap virtual system size defaults
ifneq ($(BOARD_DEFAULT_VIRT_SYSTEM_SIZE),)
    LOCAL_CFLAGS += -DDEFAULT_VIRT_SYSTEM_SIZE='"$(BOARD_DEFAULT_VIRT_SYSTEM_SIZE)"'
else
    LOCAL_CFLAGS += -DDEFAULT_VIRT_SYSTEM_SIZE='"600"'
endif
ifneq ($(BOARD_DEFAULT_VIRT_SYSTEM_MIN_SIZE),)
    LOCAL_CFLAGS += -DDEFAULT_VIRT_SYSTEM_MIN_SIZE='"$(BOARD_DEFAULT_VIRT_SYSTEM_MIN_SIZE)"'
else
    LOCAL_CFLAGS += -DDEFAULT_VIRT_SYSTEM_MIN_SIZE='"600"'
endif
ifneq ($(BOARD_DEFAULT_VIRT_SYSTEM_MAX_SIZE),)
    LOCAL_CFLAGS += -DDEFAULT_VIRT_SYSTEM_MAX_SIZE='"$(BOARD_DEFAULT_VIRT_SYSTEM_MAX_SIZE)"'
else
    LOCAL_CFLAGS += -DDEFAULT_VIRT_SYSTEM_MAX_SIZE='"1000"'
endif
# Safestrap virtual data size defaults
ifneq ($(BOARD_DEFAULT_VIRT_DATA_SIZE),)
    LOCAL_CFLAGS += -DDEFAULT_VIRT_DATA_SIZE='"$(BOARD_DEFAULT_VIRT_DATA_SIZE)"'
else
    LOCAL_CFLAGS += -DDEFAULT_VIRT_DATA_SIZE='"2000"'
endif
ifneq ($(BOARD_DEFAULT_VIRT_DATA_MIN_SIZE),)
    LOCAL_CFLAGS += -DDEFAULT_VIRT_DATA_MIN_SIZE='"$(BOARD_DEFAULT_VIRT_DATA_MIN_SIZE)"'
else
    LOCAL_CFLAGS += -DDEFAULT_VIRT_DATA_MIN_SIZE='"1000"'
endif
ifneq ($(BOARD_DEFAULT_VIRT_DATA_MAX_SIZE),)
    LOCAL_CFLAGS += -DDEFAULT_VIRT_DATA_MAX_SIZE='"$(BOARD_DEFAULT_VIRT_DATA_MAX_SIZE)"'
else
    LOCAL_CFLAGS += -DDEFAULT_VIRT_DATA_MAX_SIZE='"16000"'
endif
# Safestrap virtual cache size defaults
ifneq ($(BOARD_DEFAULT_VIRT_CACHE_SIZE),)
    LOCAL_CFLAGS += -DDEFAULT_VIRT_CACHE_SIZE='"$(BOARD_DEFAULT_VIRT_CACHE_SIZE)"'
else
    LOCAL_CFLAGS += -DDEFAULT_VIRT_CACHE_SIZE='"300"'
endif
ifneq ($(BOARD_DEFAULT_VIRT_CACHE_MIN_SIZE),)
    LOCAL_CFLAGS += -DDEFAULT_VIRT_CACHE_MIN_SIZE='"$(BOARD_DEFAULT_VIRT_CACHE_MIN_SIZE)"'
else
    LOCAL_CFLAGS += -DDEFAULT_VIRT_CACHE_MIN_SIZE='"300"'
endif
ifneq ($(BOARD_DEFAULT_VIRT_CACHE_MAX_SIZE),)
    LOCAL_CFLAGS += -DDEFAULT_VIRT_CACHE_MAX_SIZE='"$(BOARD_DEFAULT_VIRT_CACHE_MAX_SIZE)"'
else
    LOCAL_CFLAGS += -DDEFAULT_VIRT_CACHE_MAX_SIZE='"1000"'
endif
# /datamedia/media mount location for multi-boot SD calculation
ifneq ($(TW_SS_DATAMEDIA_MOUNT),)
    LOCAL_CFLAGS += -DTW_SS_DATAMEDIA_MOUNT='"$(TW_SS_DATAMEDIA_MOUNT)"'
else
    LOCAL_CFLAGS += -DTW_SS_DATAMEDIA_MOUNT='"/datamedia"'
endif
# Safestrap location
ifneq ($(SS_LOC),)
    LOCAL_CFLAGS += -DSS_LOC='"$(SS_LOC)"'
else
    LOCAL_CFLAGS += -DSS_LOC='"etc"'
endif
