LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := \
    splashmenu.cpp \
    ui.cpp

ifndef SPLASH_RECOVERY_KEY
  LOCAL_CFLAGS += -DSPLASH_RECOVERY_KEY=KEY_MENU
else
  LOCAL_CFLAGS += -DSPLASH_RECOVERY_KEY=$(SPLASH_RECOVERY_KEY)
endif
ifndef SPLASH_CONTINUE_KEY
  LOCAL_CFLAGS += -DSPLASH_CONTINUE_KEY=KEY_SEARCH
else
  LOCAL_CFLAGS += -DSPLASH_CONTINUE_KEY=$(SPLASH_CONTINUE_KEY)
endif
ifndef SPLASH_DISABLE_KEY
  LOCAL_CFLAGS += -DSPLASH_DISABLE_KEY=-1
else
  LOCAL_CFLAGS += -DSPLASH_DISABLE_KEY=$(SPLASH_DISABLE_KEY)
endif
ifndef SPLASH_DELAY
  LOCAL_CFLAGS += -DSPLASH_DELAY=8
else
  LOCAL_CFLAGS += -DSPLASH_DELAY=$(SPLASH_DELAY)
endif
ifdef SPLASH_USE_REBOOT
  LOCAL_CFLAGS += -DSPLASH_USE_REBOOT
endif

LOCAL_CFLAGS += -DMAX_ROWS=44 -DMAX_COLS=96

LOCAL_STATIC_LIBRARIES := \
    libminui_ss \
    libpixelflinger_twrp \
    libpng \
    libz \
    libc++_static \
    libc \
    libcutils \
    liblog \
    libutils \
    libm

LOCAL_MODULE := safestrapmenu
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_PACK_MODULE_RELOCATIONS := false
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_OUT)/../install-files/$(SS_LOC)/safestrap
LOCAL_UNSTRIPPED_PATH := $(TARGET_RECOVERY_OUT)/../symbols/install-files/$(SS_LOC)/safestrap
LOCAL_FORCE_STATIC_EXECUTABLE := true
include $(BUILD_EXECUTABLE)

include $(call all-makefiles-under,$(LOCAL_PATH))
